name: Deploy

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    uses: RawZ06-Studio/.github/.github/workflows/docker-build-push.yml@main
    with:
      image_name: rawz06-fr
      dokploy_app_id: rawz06-homesite-staticapp-lo79et
    secrets:
      NEXUS_LOGIN: ${{ secrets.NEXUS_LOGIN }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      DOKPLOY_TOKEN: ${{ secrets.DOKPLOY_TOKEN }}